version: "3.8"

services:
  portainer:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    networks:
      - nexusnet
    volumes:
      - nexus_data:/nexus-data
    ports:
      - "9081:8081"
      - "8082:8082"
      - "8083:8083"
networks:
  nexusnet:
    driver: bridge

volumes:
  nexus_data:
