version: "3.8"

services:
  jenkins-docker:
    image: docker:dind
    privileged: true
    container_name: jenkins-docker
    networks:
      - jenkinsnet
    environment: 
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports: 
      - "3000:3000"
      - "2376:2376"
  jenkins-blueocean:
    build: .
    container_name: jenkins-blueocean
    networks: 
      - jenkinsnet
    environment: 
      DOCKER_HOST: tcp://docker:2375
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes: 
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-home:/home

networks:
  jenkinsnet:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  jenkins-home:
